version: 2

sources:
    - name: staging
      database: stone-botany-362818
      schema: trips_data_all

      tables:
        - name: external_green_tripdata
        - name: external_yellow_tripdata


